#!/bin/bash
#
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
source /opt/rh/rh-mariadb105/enable

password=`perl -e "use NethServer::Password; print NethServer::Password::store('glpi');"`

databaseTest () {
    out=$(mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -BN -e "select count(*) from information_schema.tables where table_type = 'BASE TABLE' and table_schema = 'glpi'")
    if [[ $((out)) -gt "0" ]]; then
        return 1
    else
        return 0
    fi
}

systemctl is-active --quiet rh-mariadb105-mariadb@glpi
if [[ $? -ne 0 ]]; then
    systemctl start rh-mariadb105-mariadb@glpi
    max_wait=20
    wait=0
    while ! mysql --socket /run/rh-mariadb105-mariadb/glpi-mysql.sock -e "SHOW DATABASES" 2>/dev/null; do
        sleep 1
        wait=$((wait+1))
        if [[ $wait -ge $max_wait ]]; then
            echo "[ERROR] Can't start rh-mariadb105-mariadb@glpi"
            exit 1
        fi
    done
fi

if databaseTest ; then
    # initialize grants mysql glpi database
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "CREATE USER 'glpi'@'%' IDENTIFIED BY '$password';"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "GRANT USAGE ON *.* TO 'glpi'@'%' IDENTIFIED BY '$password';"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "CREATE DATABASE IF NOT EXISTS glpi;"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "ALTER DATABASE glpi CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "GRANT ALL PRIVILEGES ON glpi.* TO 'glpi'@'%';"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "GRANT SELECT ON mysql.time_zone_name TO 'glpi'@'%';"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "FLUSH PRIVILEGES"
    mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock -e "use glpi"
    #mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock glpi < /usr/share/glpi/install/mysql/glpi-empty.sql
    su - apache -s /bin/bash -c "/opt/rh/rh-php73/root/bin/php /usr/share/glpi/bin/console db:install --no-interaction --quiet --db-host=127.0.0.1 --db-port=8105 --db-name=glpi --db-user=glpi --db-password=$password --force --reconfigure"
    mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql --socket=/run/rh-mariadb105-mariadb/glpi-mysql.sock mysql
else
    su - apache -s /bin/bash -c "/opt/rh/rh-php73/root/bin/php /usr/share/glpi/bin/console glpi:maintenance:enable"
    su - apache -s /bin/bash -c "/opt/rh/rh-php73/root/bin/php /usr/share/glpi/bin/console db:update --no-interaction"
    su - apache -s /bin/bash -c "/opt/rh/rh-php73/root/bin/php /usr/share/glpi/bin/console glpi:maintenance:disable"
fi
